language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
jobs:
  include:
    - stage: Project install
      script: npm ci
    - stage: Project tests
      script: npm run test