language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
jobs:
  include:
    - stage: Install dependencies
      script: npm ci
    - stage: Build
      script: npm run build
    - stage: Run tests
      script: npm run test